[RELENG-7422] 📝 Add tags documentation
scality/runner-manager pull request #261
Opened 2023-06-16 21:16 UTC by gaspardmoindrot

2023-06-19 08:38 UTC, nootal requested changes

2023-06-19 08:38 UTC, nootal commented on docs/tags.md
> +compared to Grafana, which has an approximate margin of error of +/- 5%.
Why this margin of error?

2023-06-19 08:38 UTC, nootal commented on docs/tags.md
> +found in the `devinfra` repository):
Link to the specific file.

2023-06-19 08:38 UTC, nootal commented on docs/tags.md
> +- Name of the runner
Gibe an example

2023-06-19 08:38 UTC, nootal commented on docs/tags.md
> +- `tool`: `runner-manager`
Better to put this list in a table format

2023-06-19 08:38 UTC, nootal commented on docs/tags.md
> +## GCloud
Not `GCloud`. Find something that is official.

2023-06-19 08:38 UTC, nootal commented on docs/tags.md
> +- machine_type
Table format + some examples

2023-06-19 15:32 UTC, tcarmet requested changes
Same issue encountered with your PR on the exporter.

We can't add information that is internal on a public repository.
The information we can find here can only be valid in the context of the project. Everything above it should not be mentioned.

2023-06-21 15:47 UTC, tcarmet commented
We won't be merging this PR and going forward with this work.

2023-06-21 15:47 UTC, closed without merging