PTFE-693: api authentication
scality/runner-manager pull request #322
Opened 2023-08-04 16:26 UTC by Abubakarr99

2023-08-04 17:29 UTC, tcarmet reviewed
This is how I see it according to the example.

2023-08-04 17:29 UTC, tcarmet commented on runner_manager/main.py
> +        )
If we haven't configured the api key then we can proceed with the request without making any kind of authentication.

```suggestion
    if not settings.api_key:
        return settings.api_key
```

2023-08-04 17:29 UTC, tcarmet commented on runner_manager/main.py
> +    return api_key
```suggestion
    if api_key_query in [settings.api_key]:
        return api_key_query
    if api_key_header in [settings.api_key]:
        return api_key_header
    raise HTTPException(
        status_code=status.HTTP_401_UNAUTHORIZED,
        detail="Invalid API Key",
    )
```

2023-08-07 16:12 UTC, tcarmet commented on tests/api/tests_auth.py
> +    assert response.status_code == 200
```suggestion
@lru_cache()
def settings_api_key():
    return Settings(api_key="secret")


def test_private_endpoint_with_valid_api_key(fastapp, client):
    fastapp.dependency_overrides[get_settings] = settings_api_key

    headers = {"x-api-key": "secret"}
    with pytest.raises(HttpError403): # to be fixed wit accurate exception name
        client.get("/private")
    response = client.get("/private", headers=headers)
    assert response.status_code == 200
```

If it doesn't work, review this file for inspiration: https://github.com/scality/gh-actions-exporter/blob/main/tests/api/metrics/conftest.py

2023-08-07 16:12 UTC, tcarmet commented on runner_manager/main.py
> +    settings = get_settings()
```suggestion
def get_api_key(
    api_key_query: str = Security(api_key_query),
    api_key_header: str = Security(api_key_header),
    settings: Settings = Depends(get_settings),
) -> str:
```

2023-08-07 16:12 UTC, tcarmet commented on runner_manager/main.py
> +from fastapi import FastAPI, HTTPException, Response, Security, status
```suggestion
from fastapi import FastAPI, HTTPException, Response, Security, status, Depends
```

2023-08-07 17:30 UTC, tcarmet commented on runner_manager/main.py
> +from runner_manager.dependencies import get_queue, get_settings
```suggestion
from runner_manager.models.settings import Settings
from runner_manager.dependencies import get_queue, get_settings
```

2023-08-08 16:28 UTC, tcarmet commented on .github/workflows/tests.yaml
> +      API_KEY: ${{ secrets.API_KEY }}
shouldn't be set
```suggestion
```

2023-08-09 02:49 UTC, tcarmet requested changes

2023-08-09 07:23 UTC, Abubakarr99 commented on runner_manager/main.py
> +
ok

2023-08-09 15:02 UTC, tcarmet approved these changes
It LGTM, left one task that is harder to do speaking about routes, try your best on it, if it doesn't work out of the box leave it as is and we'll re-iterate on it as needed.

2023-08-09 15:02 UTC, tcarmet commented on runner_manager/main.py
> +    return f"Private Endpoint. API Key: {api_key}"
We have no use for those for now, but they are usefull for testing, would you mind trying to set them as a router inside `test_auth.py` (check `routers/_health.py` for inspiration)

Then in your test include `fastapp` `def test_my_test(fastapp, ...):`

Then proceed in adding those routes for the tests only: `fastapp.include_router(my_auth_test_router)` then execute the tests.

2023-08-11 12:29 UTC, merged